import type {
  ResearchGraphEdgeKind,
  ResearchGraphNode,
} from "@/components/research-graph/types"

export type ManualResearchGraphConnection = {
  source: string
  target: string
  relation: string
  kind: ResearchGraphEdgeKind
  strength: number
  evidence: string
  whyUseful: string
  label?: string
}

export const manualResearchGraphNodes: ResearchGraphNode[] = [
  {
    id: "artifact:outputs-decoded-local-deep-research",
    type: "artifact",
    label: "outputs/decoded/local-deep-research",
    subtitle: "Anatomia formal Local Deep Research",
    group: "decoded",
    path: "outputs/decoded/local-deep-research",
    status: "evidence",
  },
  {
    id: "artifact:adr-impeccable-001",
    type: "artifact",
    label: "ADR-IMP-001",
    subtitle: "Absorb impeccable.style as SINKRA Design Surface",
    group: "decision",
    path: "docs/bench/2026-05-18-impeccable-vs-sinkra-design-stack/ADR-001-absorb-impeccable-as-design-surface.md",
    date: "2026-05-18",
    status: "proposed",
  },
]

export const manualResearchGraphConnections: ManualResearchGraphConnection[] = [
  {
    source: "research:2026-05-06-omnichannel-helpdesk-landscape",
    target: "bench:chatwoot-vs-zendesk",
    relation: "supports",
    kind: "formal",
    strength: 0.94,
    evidence: "docs/bench/chatwoot-vs-zendesk/metadata.json:35 tech_research_source aponta para o landscape omnichannel.",
    whyUseful: "Mostra que o bench Chatwoot vs Zendesk nasce do landscape omnichannel, então a seleção dos players não é só proximidade temática.",
  },
  {
    source: "research:2026-05-06-omnichannel-helpdesk-landscape",
    target: "bench:intercom-vs-chatwoot",
    relation: "supports",
    kind: "formal",
    strength: 0.94,
    evidence: "docs/bench/intercom-vs-chatwoot/executive-report.md:5 declara Upstream para o landscape omnichannel.",
    whyUseful: "Liga o par Intercom vs Chatwoot ao mesmo funil upstream, útil para comparar pares sem perder o contexto de seleção.",
  },
  {
    source: "research:2026-05-06-omnichannel-helpdesk-landscape",
    target: "bench:octadesk-vs-zendesk",
    relation: "supports",
    kind: "formal",
    strength: 0.94,
    evidence: "docs/bench/octadesk-vs-zendesk/executive-report.md:191 lista o landscape omnichannel como fonte.",
    whyUseful: "Explica por que Octadesk entra como player BR-native contra Zendesk no pipeline omnichannel.",
  },
  {
    source: "research:2026-05-06-omnichannel-helpdesk-landscape",
    target: "bench:3-way-final-omnichannel",
    relation: "supports",
    kind: "formal",
    strength: 0.98,
    evidence: "docs/bench/3-way-final-omnichannel/executive-report-3way.md:15 diz que o tech-research selecionou o Top 6 finalista.",
    whyUseful: "Mostra a linhagem completa: pesquisa de landscape -> três benches pareados -> síntese 4-way.",
  },
  {
    source: "bench:3-way-final-omnichannel",
    target: "bench:chatwoot-vs-zendesk",
    relation: "uses_artifact",
    kind: "formal",
    strength: 0.95,
    evidence: "docs/bench/3-way-final-omnichannel/metadata.json:55 inclui artefatos de chatwoot-vs-zendesk.",
    whyUseful: "Explica que a síntese 3-way consome scorecards e gaps do par Chatwoot vs Zendesk, não recalcula do zero.",
  },
  {
    source: "bench:3-way-final-omnichannel",
    target: "bench:intercom-vs-chatwoot",
    relation: "uses_artifact",
    kind: "formal",
    strength: 0.95,
    evidence: "docs/bench/3-way-final-omnichannel/metadata.json:64 inclui artefatos de intercom-vs-chatwoot.",
    whyUseful: "Ajuda a rastrear quais evidências alimentaram as conclusões sobre Fin, in-app e pricing per-resolution.",
  },
  {
    source: "bench:3-way-final-omnichannel",
    target: "bench:octadesk-vs-zendesk",
    relation: "uses_artifact",
    kind: "formal",
    strength: 0.95,
    evidence: "docs/bench/3-way-final-omnichannel/metadata.json:73 inclui artefatos de octadesk-vs-zendesk.",
    whyUseful: "Torna explícito que os achados de BR-fit, WOZ e gaps enterprise vêm do bench Octadesk vs Zendesk.",
  },
  {
    source: "bench:octadesk-vs-zendesk",
    target: "research:2026-05-06-omnichannel-helpdesk-landscape",
    relation: "fills_gap",
    kind: "formal",
    strength: 0.9,
    evidence: "docs/bench/octadesk-vs-zendesk/executive-report.md:39 recomenda atualizar o research com pricing Octadesk corrigido.",
    whyUseful: "Mostra uma retroalimentação real: o bench corrige uma lacuna factual do research upstream.",
  },
  {
    source: "research:2026-05-16-validar-aiox-market-research-panel",
    target: "research:2026-05-16-validar-aiox-open-research-stack",
    relation: "contradicts",
    kind: "formal",
    strength: 0.96,
    evidence: "docs/research/2026-05-16-validar-aiox-market-research-panel/03-recommendations.md:168 diz que a recalibração inverteu 3 NO-GOs em GOs.",
    whyUseful: "Evita ler os dois product-discovery runs como duplicados: o segundo corrige o frame PKM/acadêmico do primeiro.",
  },
  {
    source: "research:2026-05-16-validar-aiox-market-research-panel",
    target: "research:2026-05-16-open-research-visual-platforms",
    relation: "references",
    kind: "formal",
    strength: 0.88,
    evidence: "docs/research/2026-05-16-validar-aiox-market-research-panel/00-query-original.md:6 declara cross-link técnico.",
    whyUseful: "Liga a validação de mercado ao landscape técnico que fundamentou a hipótese de produto.",
  },
  {
    source: "research:2026-05-16-validar-aiox-open-research-stack",
    target: "research:2026-05-16-open-research-visual-platforms",
    relation: "references",
    kind: "formal",
    strength: 0.88,
    evidence: "docs/research/2026-05-16-validar-aiox-open-research-stack/README.md:17 declara cross-link com a pesquisa técnica anterior.",
    whyUseful: "Mostra que o primeiro PD não surgiu isolado; ele tenta validar comercialmente um stack técnico já mapeado.",
  },
  {
    source: "research:2026-05-16-estado-da-arte-de-design-md-quais-sao-as-descobertas-que-possibilitam-cr",
    target: "bench:2026-05-18-impeccable-vs-sinkra-design-stack",
    relation: "same_decision_area",
    kind: "inferred",
    strength: 0.76,
    evidence: "Research recomenda Google DESIGN.md como formato base; bench mede URL -> DESIGN.md e Google Stitch spec.",
    whyUseful: "Conecta a pesquisa de standard DESIGN.md ao bench que decide como encaixar /design-md, /impeccable e SINKRA Design Stack.",
  },
  {
    source: "research:2026-05-06-claude-skill-design-progressive-disclosure",
    target: "bench:2026-05-18-impeccable-vs-sinkra-design-stack",
    relation: "same_decision_area",
    kind: "inferred",
    strength: 0.66,
    evidence: "Research descreve progressive disclosure; bench pontua cognitive-load.md com progressive disclosure check.",
    whyUseful: "Ajuda a encontrar a ponte entre design de skills e o vocabulário/carga cognitiva avaliado no bench de design.",
  },
  {
    source: "research:2026-04-10-v0-opensource-alternatives",
    target: "bench:v0-design-pipeline",
    relation: "same_decision_area",
    kind: "inferred",
    strength: 0.8,
    evidence: "Research busca replicar qualidade v0 sem código proprietário; bench diz que o gap SINKRA-v0 é automação pós-geração.",
    whyUseful: "Liga o mapa de alternativas OSS ao bench que transforma esse mapa em decisão sobre pipeline de execução.",
  },
  {
    source: "research:2026-05-16-eddie-ai-marketing",
    target: "bench:submagic-vs-eddie-ai",
    relation: "extends",
    kind: "formal",
    strength: 0.93,
    evidence: "docs/research/2026-05-16-eddie-ai-marketing/README.md:7 diz que a comparação Submagic vs Eddie já está no bench.",
    whyUseful: "Mostra que a pesquisa de marketing aprofunda GTM e copy depois que o bench já separou features e substituição OSS.",
  },
  {
    source: "bench:slides-creator-open-source-absorption",
    target: "bench:presenton-vs-gamma",
    relation: "references",
    kind: "formal",
    strength: 0.9,
    evidence: "docs/bench/slides-creator-open-source-absorption/slide-creator-skill-blueprint.md:5 cita presenton-vs-gamma como fonte.",
    whyUseful: "Mostra que a absorção open-source de slides reutiliza o bench Presenton vs Gamma como referência de produto/UX.",
  },
  {
    source: "bench:2026-05-19-slide-templates-categories-matrix",
    target: "bench:slides-creator-open-source-absorption",
    relation: "uses_artifact",
    kind: "formal",
    strength: 0.9,
    evidence: "docs/bench/2026-05-19-slide-templates-categories-matrix/metadata.json:21 lista slides-creator-open-source-absorption.",
    whyUseful: "Explica que a matriz de templates é uma continuação tática do inventário de absorção de slide creator.",
  },
  {
    source: "bench:2026-05-19-slide-templates-categories-matrix",
    target: "bench:presenton-vs-gamma",
    relation: "uses_artifact",
    kind: "formal",
    strength: 0.88,
    evidence: "docs/bench/2026-05-19-slide-templates-categories-matrix/metadata.json:24 lista presenton-vs-gamma.",
    whyUseful: "Mostra que Presenton segue como evidência para taxonomia de templates e não apenas como comparação isolada contra Gamma.",
  },
  {
    source: "bench:2026-05-19-local-deep-research-absorption",
    target: "artifact:outputs-decoded-local-deep-research",
    relation: "uses_artifact",
    kind: "formal",
    strength: 0.94,
    evidence: "docs/bench/2026-05-19-local-deep-research-absorption/relationship-to-decoded.md:3 diz que os dois são complementares.",
    whyUseful: "Mostra que a decisão de absorção LDR depende da anatomia decoded como artefato de evidência, não só do bench.",
  },
  {
    source: "artifact:adr-impeccable-001",
    target: "bench:2026-05-18-impeccable-vs-sinkra-design-stack",
    relation: "supports",
    kind: "formal",
    strength: 0.9,
    evidence: "docs/bench/2026-05-18-impeccable-vs-sinkra-design-stack/ADR-001-absorb-impeccable-as-design-surface.md:23 registra a decisão de absorção.",
    whyUseful: "Torna o ADR visível como artefato decisório conectado ao bench que o gerou.",
  },
]
